version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB_NAME: wallet_db
      POSTGRES_DB_HOST: host.docker.internal
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: password
      JWT_SECRET_KEY: 1234567$$890qwertyui%%op
      SERVER_TIMEZONE: Asia/Jakarta
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
